=== pacharanero/mim/Schemas/QUPA_MT000003UK02.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns="urn:hl7-org:v3" xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="urn:hl7-org:v3"
           elementFormDefault="qualified"><!--
*****************************************************************************************************************
* 		XML schema for message type : QUPA_MT000003UK02.
* 
*		Source information:
*		Generated by Schema builder version : 
*    	Created on: 
*   
* 		Copyright (c) 2002, 2003, 2004, 2005, 2006 Health Level Seven. All rights reserved.
*  	Redistribution and use in source and binary forms, with or without
*  	modification, are permitted provided that the following conditions
*  	are met:
*  		1. Redistributions of source code must retain the above copyright
*     		notice, this list of conditions and the following disclaimer.
*  		2. Redistributions in binary form must reproduce the above copyright
*     		notice, this list of conditions and the following disclaimer in the
*     		documentation and/or other materials provided with the distribution.
*  		3. All advertising materials mentioning features or use of this software
*     		must display the following acknowledgement:
*       This product includes software developed by Health Level Seven.
*  	THIS SOFTWARE IS PROVIDED BY HEALTH LEVEL SEVEN, INC. AND CONTRIBUTORS "AS IS" AND
*  	ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
*  	IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
*  	ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
*  	FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
*  	DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
*  	OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
*  	HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
*  	LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
*  	OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
*  	SUCH DAMAGE.
*
********************************************************************************************************************
	  --><xs:include schemaLocation="../dt/infrastructureRoot.xsd"/>
   <xs:include schemaLocation="../dt/NHSVocab.xsd"/>
   <xs:include schemaLocation="../dt/datatypeflavours.xsd"/>
   <xs:element name="query" type="QUPA_MT000003UK02.Query"/>
   <xs:complexType name="QUPA_MT000003UK02.HistoricDataIndicator">
      <xs:sequence>
         <xs:group ref="InfrastructureRootElements"/>
         <xs:element name="semanticsText" type="ST" minOccurs="1" maxOccurs="1"
                     fixed="HistoricDataIndicator"/>
         <xs:element name="value" minOccurs="1" maxOccurs="1">
            <xs:complexType>
               <xs:complexContent>
                  <xs:restriction base="CV">
                     <xs:attribute name="code" use="required" type="HistoricDataIndicator_code"/>
                     <xs:attribute name="displayName" use="prohibited" type="st"/>
                     <xs:attribute name="codeSystem" use="required" type="uid"
                                   fixed="2.16.840.1.113883.2.1.3.2.4.17.36"/>
                     <xs:attribute name="codeSystemName" type="st" use="prohibited"/>
                     <xs:attribute name="codeSystemVersion" type="st" use="prohibited"/>
                     <xs:attribute name="updateMode" type="cs" use="prohibited"/>
                     <xs:attribute name="nullFlavor" type="cs_NullFlavor" use="prohibited"/>
                  </xs:restriction>
               </xs:complexContent>
            </xs:complexType>
         </xs:element>
      </xs:sequence>
      <xs:attributeGroup ref="InfrastructureRootAttributes"/>
   </xs:complexType>
   <xs:complexType name="QUPA_MT000003UK02.Person.id">
      <xs:sequence>
         <xs:group ref="InfrastructureRootElements"/>
         <xs:element name="semanticsText" type="ST" minOccurs="1" maxOccurs="1" fixed="Person.id"/>
         <xs:element name="value" type="II.NPfIT.oid.mandatory" minOccurs="1" maxOccurs="1"/>
      </xs:sequence>
      <xs:attributeGroup ref="InfrastructureRootAttributes"/>
   </xs:complexType>
   <xs:complexType name="QUPA_MT000003UK02.Query">
      <xs:sequence>
         <xs:group ref="InfrastructureRootElements"/>
         <xs:element name="historicDataIndicator" type="QUPA_MT000003UK02.HistoricDataIndicator"
                     minOccurs="1"
                     maxOccurs="1"/>
         <xs:element name="person.id" type="QUPA_MT000003UK02.Person.id" minOccurs="1" maxOccurs="1"/>
         <xs:element name="retrievalItem" type="QUPA_MT000003UK02.RetrievalItem" nillable="true"
                     minOccurs="0"
                     maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attributeGroup ref="InfrastructureRootAttributes"/>
   </xs:complexType>
   <xs:complexType name="QUPA_MT000003UK02.RetrievalItem">
      <xs:sequence>
         <xs:group ref="InfrastructureRootElements"/>
         <xs:element name="semanticsText" type="ST" minOccurs="1" maxOccurs="1"/>
      </xs:sequence>
      <xs:attributeGroup ref="InfrastructureRootAttributes"/>
   </xs:complexType>
</xs:schema>

=== pacharanero/mim/Examples/PDS/QUPA_EX000003UK02_03.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- This example message is provided for illustrative purposes only. It has had no clinical validation nor is it guaranteed to be fully compliant with the written message specification. Where there are conflicts with the written message specification or schema, the specification or schema shall be considered to take precedence. -->
<query xmlns="urn:hl7-org:v3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:hl7-org:v3 ../../Schemas/QUPA_MT000003UK02.xsd">
	<historicDataIndicator>
		<!-- To indicate "Retrieve all historic information on requested parameters" -->
		<semanticsText>HistoricDataIndicator</semanticsText>
		<value code="1" codeSystem="2.16.840.1.113883.2.1.3.2.4.17.36"/>
	</historicDataIndicator>
	<person.id>
		<!-- NHS number -->
		<semanticsText>Person.id</semanticsText>
		<value root="2.16.840.1.113883.2.1.4.1" extension="9999999484"/>
	</person.id>
	<retrievalItem>
		<!-- To indicate retrieve all proxy details -->
		<semanticsText>Proxy</semanticsText>
	</retrievalItem>
</query>
