=== pacharanero/mim/Schemas/QURX_MT000005UK01.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:hl7-org:v3" elementFormDefault="qualified" xmlns="urn:hl7-org:v3" xmlns:hl7="urn:hl7-org:v3">
   <xs:include schemaLocation="../dt/datatypes.xsd"/>
   <xs:include schemaLocation="../voc/voc.xsd"/>
   <xs:annotation>
      <xs:documentation>
		Generated using schema builder version 1.21p12.
		Stylesheets:
		
		RoseTreeToMIFStaticModel.xsl version: 1.1
		SplitModels.xsl version: 1.1
		AssocInMif.xsl version:1.1
		StaticMifToXsd.xsl version 1.1</xs:documentation>
   </xs:annotation><!--
*****************************************************************************************************************
* XML schema for message type .
* Generated by XMLITS version 1.21p12, Copyright (C) 2002, 2003 by Health Level 7, Inc.
*
* Copyright (c) 2002, 2003, Health Level Seven. All rights reserved.
*  Redistribution and use in source and binary forms, with or without
*  modification, are permitted provided that the following conditions
*  are met:
*  1. Redistributions of source code must retain the above copyright
*     notice, this list of conditions and the following disclaimer.
*  2. Redistributions in binary form must reproduce the above copyright
*     notice, this list of conditions and the following disclaimer in the
*     documentation and/or other materials provided with the distribution.
*  3. All advertising materials mentioning features or use of this software
*     must display the following acknowledgement:
*       This product includes software developed by Health Level Seven.
*  THIS SOFTWARE IS PROVIDED BY HEALTH LEVEL SEVEN, INC. AND CONTRIBUTORS "AS IS" AND
*  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
*  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
*  ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
*  FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
*  DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
*  OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
*  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
*  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
*  OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
*  SUCH DAMAGE.
*
********************************************************************************************************************
-->
   <xs:element name="query" type="QURX_MT000005UK01.Query"/>
   <xs:complexType name="QURX_MT000005UK01.Query">
      <xs:sequence>
         <xs:element type="QURX_MT000005UK01.Organization.id" minOccurs="1" maxOccurs="1" name="organization.id"/>
         <xs:element type="QURX_MT000005UK01.Prescription.id" minOccurs="1" maxOccurs="1" name="prescription.id"/>
         <xs:element type="QURX_MT000005UK01.Prescription.repeatNumber" minOccurs="0" maxOccurs="1" name="prescription.repeatNumber"/>
         <xs:element type="QURX_MT000005UK01.RequesterOrganizationType" minOccurs="1" maxOccurs="1" name="requesterOrganizationType"/>
      </xs:sequence>
      <xs:attribute name="type" type="Classes" default="QueryByParameter"/>
      <xs:attribute name="typeID" use="optional">
         <xs:simpleType>
            <xs:list itemType="oid"/>
         </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="realmCode" use="optional">
         <xs:simpleType>
            <xs:list itemType="cs"/>
         </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="nullFlavor" type="cs" use="optional"/>
   </xs:complexType>
   <xs:complexType name="QURX_MT000005UK01.Organization.id">
      <xs:sequence>
         <xs:element name="value" type="II" minOccurs="1" maxOccurs="1"/>
         <xs:element name="semanticsText" type="ST" minOccurs="1" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="type" type="Classes" default="ParameterItem"/>
      <xs:attribute name="typeID" use="optional">
         <xs:simpleType>
            <xs:list itemType="oid"/>
         </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="realmCode" use="optional">
         <xs:simpleType>
            <xs:list itemType="cs"/>
         </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="nullFlavor" type="cs" use="optional"/>
   </xs:complexType>
   <xs:complexType name="QURX_MT000005UK01.Prescription.id">
      <xs:sequence>
         <xs:element name="value" type="II" minOccurs="1" maxOccurs="1"/>
         <xs:element name="semanticsText" type="ST" minOccurs="1" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="type" type="Classes" default="ParameterItem"/>
      <xs:attribute name="typeID" use="optional">
         <xs:simpleType>
            <xs:list itemType="oid"/>
         </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="realmCode" use="optional">
         <xs:simpleType>
            <xs:list itemType="cs"/>
         </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="nullFlavor" type="cs" use="optional"/>
   </xs:complexType>
   <xs:complexType name="QURX_MT000005UK01.Prescription.repeatNumber">
      <xs:sequence>
         <xs:element name="value" type="INT" minOccurs="1" maxOccurs="1"/>
         <xs:element name="semanticsText" type="ST" minOccurs="1" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="type" type="Classes" default="ParameterItem"/>
      <xs:attribute name="typeID" use="optional">
         <xs:simpleType>
            <xs:list itemType="oid"/>
         </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="realmCode" use="optional">
         <xs:simpleType>
            <xs:list itemType="cs"/>
         </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="nullFlavor" type="cs" use="optional"/>
   </xs:complexType>
   <xs:complexType name="QURX_MT000005UK01.RequesterOrganizationType">
      <xs:sequence>
         <xs:element name="value" type="CV" minOccurs="1" maxOccurs="1"/>
         <xs:element name="semanticsText" type="ST" minOccurs="1" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="type" type="Classes" default="ParameterItem"/>
      <xs:attribute name="typeID" use="optional">
         <xs:simpleType>
            <xs:list itemType="oid"/>
         </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="realmCode" use="optional">
         <xs:simpleType>
            <xs:list itemType="cs"/>
         </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="nullFlavor" type="cs" use="optional"/>
   </xs:complexType>
</xs:schema>

=== pacharanero/mim/Examples/Medication Management/QURX_EX000005UK01_01.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
This example message is provided for illustrative purposes only. It has had no clinical validation. Whilst every effort has been taken to ensure that the examples are consistent with the message specification contained within the MiM, where there are conflicts with the written message specification or schema, the specification or schema shall be considered to take precedence.
-->
<query xmlns="urn:hl7-org:v3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:hl7-org:v3
../../Schemas/QURX_MT000005UK01.xsd">
	<organization.id>
		<value root="1.2.826.0.1285.0.1.10" extension="AB123"/>
		<semanticsText>Organization.id</semanticsText>
	</organization.id>
	<prescription.id>
		<value root="45D2E9DD-DA11-C266-A426-447C68D3D33A"/>
		<semanticsText>Prescription.id</semanticsText>
	</prescription.id>
	<requesterOrganizationType>
		<value code="003" codeSystem="2.16.840.1.113883.2.1.3.2.4.17.128"/>
		<semanticsText>RequesterOrganizationType</semanticsText>
	</requesterOrganizationType>
</query>
